stages:
    - build_stage
    - deploy_stage

build :
    stage: build_stage
    image : node
    script :
        - npm install
    artifacts :
        paths:
            - node_modules
            - package-lock.json

deploy :
    image: node
    stage: deploy_stage
    script :
        - node index.js >/dev/null 2>&1&